//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ispit
    {
        public int id { get; set; }
        public System.DateTime vreme { get; set; }
        public int idPredmet { get; set; }
        public int idStudent { get; set; }
        public short polozen { get; set; }
    
        public virtual Predmet Predmet { get; set; }
        public virtual Student Student { get; set; }
    }
}
